### ISSUE TITLE
automatically populate holiday time into timesheets

### ISSUE THREAD

**Issue by searls** [testdouble/present#71] opened 2015-04-28 15:41 UTC
This would have been easier if it weren't for the differing holidays between Canadian and US employees

- [ ] add a country field to User
- [ ] populate a set of holidays (date, applicable countries)
- [ ] use something like the business_time gem to deal with observing holidays that fall on weekends, etc
- [ ] at timesheet-create-time if any entry days should be a holiday, mark them as a full present holiday and mark any default billable project as absent.

**Comment by searls** [comment] 2015-04-28 15:44
@tkaufman please review this to see if I missed something in what you asked for

**Comment by tkaufman** [comment] 2016-10-24 17:36
This is good and I tried to spike it and it's hard for our schedules. This is also a duplicate of #4

**Closed** 2016-10-24 17:36 UTC
Labels: duplicate
