### ISSUE TITLE
Extra Holiday and Vacation selections after "Update Timesheet"

### ISSUE THREAD

**Issue by bostonaholic** [testdouble/present#44] opened 2014-10-18 16:32 UTC
I finished filling out the summary notes for the current (10/12/14—10/18/14) week. After the page redirect, this is what it looks like. It still does even after a page refresh.

![screen shot 2014-10-18 at 10 28 22 am](https://cloud.githubusercontent.com/assets/362146/4690354/5d4db1dc-56e4-11e4-800a-8e70c35d7248.png)

**Comment by searls** [comment] 2015-01-06 19:33
This turned out to be a dupe of #46 and was fixed by https://github.com/testdouble/present/commit/51358a9278abc31f58333fbf556c2a52c89a0b74

Worst case now when it happens is that you may see an application error screen before you refresh.

**Closed by searls** 2015-01-06 19:33 UTC
Labels: bug, ready
